CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_BATTERY_REPORTING=y

# BLE connection parameters tuning (Optimized for Direct PC connection)
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y
CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT=5000
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# My config begins here
# ヒープメモリの拡張
CONFIG_HEAP_MEM_POOL_SIZE=24576

# Bluetooth (Zephyr BLE stack) Memory / Buffer Tuning
CONFIG_BT_RX_STACK_SIZE=2560
CONFIG_BT_HCI_TX_STACK_SIZE_WITH_PROMPT=y
CONFIG_BT_HCI_TX_STACK_SIZE=1536

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#CONFIG_BT_CTLR_TX_PWR_PLUS_12=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=y

CONFIG_ZMK_SLEEP=n
#CONFIG_BT_PERIPHERAL_PREF_MAX_INT=24
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=600
# My config end
